---
hammer_devel_ruby_version: 2.3.1
hammer_devel_server_group: "server-{{ inventory_hostname }}"
hammer_devel_server: "centos7-katello-devel"
hammer_devel_server_protocol: 'https'
hammer_devel_server_port: 443
hammer_devel_host: "{{ hammer_devel_server_protocol }}://{{ hammer_devel_server }}:{{ hammer_devel_server_port }}"
hammer_devel_username: admin
hammer_devel_password: changeme
hammer_devel_github_fork_remote_name: "{{ hammer_devel_github_username }}"
hammer_devel_repositories:
  - theforeman/hammer-cli
  - theforeman/hammer-cli-foreman
  - theforeman/hammer-cli-foreman-admin
  - theforeman/hammer-cli-foreman-tasks
  - theforeman/hammer_cli_foreman_remote_execution
  - theforeman/hammer-cli-foreman-virt-who-configure
  - theforeman/hammer_cli_foreman_azure_rm
  - theforeman/hammer-cli-foreman-rh-cloud
  - katello/hammer-cli-katello
hammer_devel_local_gems: |-
  gem 'hammer_cli'
    gem 'hammer_cli_katello'
    gem 'hammer_cli_foreman_admin'
    gem 'hammer_cli_foreman_tasks'
    gem 'hammer_cli_foreman_remote_execution'
    gem 'hammer_cli_foreman_virt_who_configure'
    gem 'hammer_cli_foreman_azure_rm'
    gem 'hammer_cli_foreman_rh_cloud'

hammer_config_items:
  - { key: "hammer-cli-foreman", value: "foreman.yml" }
  - { key: "hammer-cli-foreman-admin", value: "foreman_admin.yml" }
  - { key: "hammer-cli-katello", value: "katello.yml" }
  - { key: "hammer-cli-foreman-rh-cloud", value: "foreman_rh_cloud.yml" }
  - { key: "hammer_cli_foreman_remote_execution", value: "foreman_remote_execution.yml" }
  - { key: "hammer-cli-foreman-virt-who-configure", value: "foreman_virt_who_configure.yml" }
  - { key: "hammer_cli_foreman_azure_rm", value: "foreman_azure_rm.yml" }