---
- name: 'Add hammer config directory'
  file: path=~/.hammer state=directory

- name: 'Add hammer module config directory'
  file: path=~/.hammer/cli.modules.d state=directory

- name: 'Configure hammer'
  command: cp ~/hammer-cli/config/cli_config.template.yml ~/.hammer/cli_config.yml
  args:
    creates: ~/.hammer/cli_config.yml

- name: Configure Hammer CLI Foreman and modules
  command: cp ~/"{{ item.key }}"/config/"{{ item.value }}" ~/.hammer/cli.modules.d/
  args:
    creates: ~/.hammer/cli.modules.d/"{{ item.value }}"
  loop: "{{ hammer_config_items }}"
  loop_control:
    loop_var: item

- name: 'Configure hammer-cli-foreman-admin logging core'
  command: cp ~/hammer-cli-foreman-admin/config/cli.modules.d/foreman_admin_logging_core.yml ~/.hammer/cli.modules.d/
  args:
    creates: ~/.hammer/cli.modules.d/foreman_admin_logging_core.yml
  when: ('theforeman/hammer-cli-foreman-admin' in hammer_devel_repositories)

- name: 'Configure hammer-cli-foreman-admin logging for katello'
  command: cp ~/hammer-cli-foreman-admin/config/cli.modules.d/foreman_admin_logging_katello.yml ~/.hammer/cli.modules.d/
  args:
    creates: ~/.hammer/cli.modules.d/foreman_admin_logging_katello.yml
  when: ('theforeman/hammer-cli-foreman-admin' in hammer_devel_repositories)

- name: 'Update hammer-cli-foreman host'
  lineinfile:
    dest: ~/.hammer/cli.modules.d/foreman.yml
    line: '  :host: {{ hammer_devel_host }}'
    regexp: 'host'

- name: 'Update hammer-cli-foreman username'
  lineinfile:
    dest: ~/.hammer/cli.modules.d/foreman.yml
    line: '  :username: {{ hammer_devel_username }}'
    regexp: 'username'

- name: 'Update hammer-cli-foreman password'
  lineinfile:
    dest: ~/.hammer/cli.modules.d/foreman.yml
    line: '  :password: {{ hammer_devel_password }}'
    regexp: 'password'

- name: 'Alias hammer'
  lineinfile: dest=~/.bash_profile line="alias hammer='BUNDLE_GEMFILE=~/hammer-cli-foreman/Gemfile bundle exec hammer'"

- name: 'Alias rake'
  lineinfile: dest=~/.bash_profile line="alias rake='bundle exec rake'"
